### PR TITLE
prometheus exporter: remove non-ucum units from conversion

### PR DESCRIPTION
**Pull request by dashpole**
Description:

Discovered during https://github.com/open-telemetry/opentelemetry-go/pull/4374#pullrequestreview-1548606912.

`B` means `bel` in UCUM, so `MB` is `megabel`, for example. `$` is also not UCUM.

https://ucum.org/ucum#section-Alphabetic-Index-By-Symbol

### CODE REVIEW

**Comment by dashpole** [comment]
Failure seems unrelated: 

```
> Task :sdk:metrics:compileTestJava
/home/runner/work/opentelemetry-java/opentelemetry-java/sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/descriptor/MetricDescriptorTest.java:86: error: cannot find symbol
                Advice.create(Arrays.asList(1.0, 2.0))));
                      ^
  symbol:   method create(List<Double>)
  location: class Advice
1 error

> Task :sdk:metrics:compileTestJava FAILED
```

**Comment by jack-berg** [comment]
> Failure seems unrelated:

Yup, bad merge. Fixed in #5721. Pull in main after that is merged.

**Review by mateuszrzeszutek — APPROVED** [review]

**Review by jack-berg — APPROVED** [review]
